# Generated by Django 5.2.2 on 2026-04-20 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        help_text="Formatted token e.g. OPD-A042", max_length=20
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Daily numeric sequence per department+priority"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("kiosk", "Kiosk Self Check-in"),
                            ("counter", "Counter"),
                            ("web", "Web"),
                            ("app", "Mobile App"),
                        ],
                        default="counter",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("elderly", "Elderly"),
                            ("disabled", "Disabled"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("in_service", "In Service"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skip_count", models.PositiveSmallIntegerField(default=0)),
                ("notify_lead_minutes", models.PositiveSmallIntegerField(default=10)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens",
                        to="core.counter",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens",
                        to="core.department",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens",
                        to="core.patient",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("called", "Called"),
                            ("recalled", "Re-called"),
                            ("skipped", "Skipped"),
                            ("started", "Service Started"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                            ("transferred", "Transferred"),
                            ("notified", "Notified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.counter",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="queues.token",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("last_normal_seq", models.PositiveIntegerField(default=0)),
                ("last_priority_seq", models.PositiveIntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_counters",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["department", "status"], name="queues_toke_departm_b471f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["status", "priority"], name="queues_toke_status_78e0c5_idx"
            ),
        ),
    ]
