# Generated by Django 5.2.2 on 2026-04-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQueueStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("tokens_issued", models.PositiveIntegerField(default=0)),
                ("tokens_served", models.PositiveIntegerField(default=0)),
                ("tokens_skipped", models.PositiveIntegerField(default=0)),
                ("tokens_no_show", models.PositiveIntegerField(default=0)),
                ("avg_wait_seconds", models.PositiveIntegerField(default=0)),
                ("avg_service_seconds", models.PositiveIntegerField(default=0)),
                ("avg_tat_seconds", models.PositiveIntegerField(default=0)),
                ("peak_hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("department", "date")},
            },
        ),
    ]
