# Generated by Django 5.2.2 on 2026-04-21 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=160)),
                (
                    "registration_number",
                    models.CharField(
                        help_text="PMDC/NMC license #", max_length=60, unique=True
                    ),
                ),
                ("specialisation", models.CharField(blank=True, max_length=120)),
                (
                    "qualifications",
                    models.CharField(
                        blank=True, help_text="e.g. MBBS, MD (Medicine)", max_length=160
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "abha_address",
                    models.CharField(
                        blank=True,
                        help_text="Doctor's own ABHA address (e.g. drsmith@abdm)",
                        max_length=100,
                    ),
                ),
                (
                    "hpr_id",
                    models.CharField(
                        blank=True,
                        help_text="Healthcare Professional Registry ID (ABDM)",
                        max_length=60,
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("avg_consult_minutes", models.PositiveIntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctors",
                        to="core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                ("slot_minutes", models.PositiveIntegerField(default=15)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new", "New Consultation"),
                            ("followup", "Follow-up"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("checked_in", "Checked-in"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Chief complaint / reason for visit",
                        max_length=255,
                    ),
                ),
                (
                    "booked_via",
                    models.CharField(
                        default="counter",
                        help_text="counter | web | app | kiosk",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("token_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="core.department",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="core.patient",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="opd.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_minutes", models.PositiveIntegerField(default=15)),
                ("room", models.CharField(blank=True, max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="opd.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["doctor__full_name", "weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drug_name", models.CharField(max_length=160)),
                (
                    "strength",
                    models.CharField(
                        blank=True, help_text="e.g. 500 mg", max_length=60
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("iv", "IV"),
                            ("im", "IM"),
                            ("sc", "Subcutaneous"),
                            ("topical", "Topical"),
                            ("inhaled", "Inhaled"),
                        ],
                        default="oral",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("OD", "Once a day"),
                            ("BD", "Twice a day"),
                            ("TDS", "Three times a day"),
                            ("QID", "Four times a day"),
                            ("HS", "At bedtime"),
                            ("SOS", "As needed"),
                            ("STAT", "Immediately"),
                        ],
                        default="OD",
                        max_length=10,
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=1)),
                ("instructions", models.CharField(blank=True, max_length=255)),
                (
                    "rx_norm_code",
                    models.CharField(
                        blank=True,
                        help_text="RxNorm / SNOMED code for FHIR",
                        max_length=30,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="opd.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit_number",
                    models.CharField(
                        help_text="Human-readable, e.g. OPD-V-20260421-0007",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("chief_complaints", models.TextField(blank=True)),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="History of present illness / past medical history",
                    ),
                ),
                ("examination", models.TextField(blank=True)),
                ("advice", models.TextField(blank=True)),
                ("follow_up_on", models.DateField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("abdm_care_context_ref", models.CharField(blank=True, max_length=120)),
                ("abdm_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit",
                        to="opd.appointment",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="core.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="opd.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="prescription",
            name="visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="opd.visit",
            ),
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_name", models.CharField(max_length=160)),
                (
                    "test_code",
                    models.CharField(
                        blank=True, help_text="LOINC code (ABDM FHIR)", max_length=40
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("collected", "Sample Collected"),
                            ("resulted", "Result Available"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        default="routine",
                        help_text="routine | urgent | stat",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("result_value", models.CharField(blank=True, max_length=255)),
                ("result_at", models.DateTimeField(blank=True, null=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("final", "Final"),
                            ("differential", "Differential"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "icd10_code",
                    models.CharField(
                        blank=True,
                        help_text="ICD-10 classification code",
                        max_length=20,
                    ),
                ),
                (
                    "snomed_code",
                    models.CharField(
                        blank=True,
                        help_text="SNOMED CT code (used in ABDM FHIR bundles)",
                        max_length=30,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("pulse_bpm", models.PositiveIntegerField(blank=True, null=True)),
                ("systolic_bp", models.PositiveIntegerField(blank=True, null=True)),
                ("diastolic_bp", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "spo2",
                    models.PositiveIntegerField(blank=True, help_text="%", null=True),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="opd.visit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "scheduled_at"], name="opd_appoint_doctor__ab0023_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "scheduled_at"],
                name="opd_appoint_patient_5f97a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="opd_appoint_status_617118_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "weekday", "start_time")},
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient", "opened_at"], name="opd_visit_patient_a16025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["doctor", "opened_at"], name="opd_visit_doctor__354a89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(fields=["status"], name="opd_visit_status_7e1d87_idx"),
        ),
    ]
