# Generated by Django 5.2.2 on 2026-04-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HMISProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("generic", "Generic REST"),
                            ("ehospital", "NIC e-Hospital"),
                            ("medixcel", "Medixcel"),
                            ("nextgen", "NextGen"),
                            ("fhir", "FHIR R4"),
                        ],
                        default="generic",
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="Root URL of the HMIS REST API"),
                ),
                (
                    "auth_type",
                    models.CharField(
                        default="bearer",
                        help_text="bearer | basic | api_key | oauth2",
                        max_length=20,
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=120)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(blank=True, max_length=255)),
                (
                    "facility_id",
                    models.CharField(
                        blank=True, help_text="Hospital code in the HMIS", max_length=80
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="HMAC secret used for inbound webhook verification",
                        max_length=80,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="HMISEncounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hmis_encounter_id", models.CharField(blank=True, max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmis_encounters",
                        to="core.patient",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hmis_encounters",
                        to="queues.token",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="hmis.hmisprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HMISPatientLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hmis_patient_id",
                    models.CharField(
                        help_text="Primary patient id in the HMIS", max_length=80
                    ),
                ),
                ("hmis_mrn", models.CharField(blank=True, max_length=80)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Last snapshot from HMIS (for debugging)",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmis_links",
                        to="core.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_links",
                        to="hmis.hmisprovider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "hmis_mrn"],
                        name="hmis_hmispa_provide_0b82cd_idx",
                    )
                ],
                "unique_together": {("provider", "hmis_patient_id")},
            },
        ),
        migrations.CreateModel(
            name="HMISAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hmis_appointment_id", models.CharField(max_length=80)),
                ("department_code", models.CharField(blank=True, max_length=40)),
                ("service_code", models.CharField(blank=True, max_length=40)),
                ("doctor_name", models.CharField(blank=True, max_length=120)),
                ("doctor_hmis_id", models.CharField(blank=True, max_length=80)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("arrived", "Arrived"),
                            ("checked_in", "Checked In"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hmis_appointments",
                        to="core.patient",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hmis_appointments",
                        to="queues.token",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="hmis.hmisprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="hmis_hmisap_status_fc8605_idx",
                    ),
                    models.Index(
                        fields=["patient"], name="hmis_hmisap_patient_f86691_idx"
                    ),
                ],
                "unique_together": {("provider", "hmis_appointment_id")},
            },
        ),
        migrations.CreateModel(
            name="HMISTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        help_text="patient.lookup, appointment.list, encounter.push, webhook.status…",
                        max_length=80,
                    ),
                ),
                ("method", models.CharField(default="POST", max_length=10)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hmis_transactions",
                        to="core.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="hmis.hmisprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "operation"],
                        name="hmis_hmistr_provide_7e1a98_idx",
                    ),
                    models.Index(
                        fields=["direction", "created_at"],
                        name="hmis_hmistr_directi_c6339d_idx",
                    ),
                ],
            },
        ),
    ]
