# Generated by Django 5.2.2 on 2026-04-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABDMTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("auth", "Gateway Auth"),
                            ("otp_request", "OTP Request"),
                            ("otp_verify", "OTP Verify"),
                            ("abha_create", "ABHA Create"),
                            ("abha_fetch", "ABHA Fetch"),
                            ("abha_link", "ABHA Link"),
                            ("consent_request", "Consent Request"),
                            ("consent_fetch", "Consent Fetch"),
                            ("care_context_link", "Care Context Link"),
                            ("hip_share", "HIP Share Bundle"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=120)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abdm_txns",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABHAProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abha_number",
                    models.CharField(
                        help_text="14 digit ABHA number, formatted XX-XXXX-XXXX-XXXX",
                        max_length=17,
                        unique=True,
                    ),
                ),
                (
                    "abha_address",
                    models.CharField(
                        help_text="Self-chosen ABHA address e.g. alice@abdm",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=60)),
                ("middle_name", models.CharField(blank=True, max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("kyc_verified", models.BooleanField(default=False)),
                (
                    "kyc_method",
                    models.CharField(
                        blank=True,
                        help_text="aadhaar | mobile | driving_license",
                        max_length=20,
                    ),
                ),
                ("photo_base64", models.TextField(blank=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "eka_care_user_id",
                    models.CharField(
                        blank=True, help_text="Eka Care internal user id", max_length=80
                    ),
                ),
                (
                    "x_token",
                    models.TextField(
                        blank=True, help_text="ABDM patient token (short-lived)"
                    ),
                ),
                ("x_token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abha",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="Hospital-assigned unique ref (e.g. visit number)",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="Human description — 'Consultation 21 Apr 2026'",
                        max_length=160,
                    ),
                ),
                (
                    "hi_types",
                    models.JSONField(
                        default=list, help_text="Record types included in this context"
                    ),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("eka_context_id", models.CharField(blank=True, max_length=120)),
                (
                    "abha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_contexts",
                        to="abdm.abhaprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester_name",
                    models.CharField(default="AIIMS Hospital", max_length=120),
                ),
                (
                    "requester_id",
                    models.CharField(blank=True, help_text="HIP/HIU id", max_length=60),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("CAREMGT", "Care Management"),
                            ("BTG", "Break the Glass"),
                            ("PUBHLTH", "Public Health"),
                            ("HPAYMT", "Healthcare Payment"),
                            ("DSRCH", "Disease Specific Research"),
                            ("PATRQT", "Patient Requested"),
                        ],
                        default="CAREMGT",
                        max_length=20,
                    ),
                ),
                (
                    "hi_types",
                    models.JSONField(
                        default=list,
                        help_text="Health Information types, e.g. ['Prescription','DiagnosticReport']",
                    ),
                ),
                ("date_from", models.DateTimeField(blank=True, null=True)),
                ("date_to", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "consent_request_id",
                    models.CharField(
                        blank=True, help_text="ABDM gateway id", max_length=100
                    ),
                ),
                ("consent_artefact_id", models.CharField(blank=True, max_length=100)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecordLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="opd.Visit id (soft link)", null=True
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("OPConsultation", "OP Consultation"),
                            ("Prescription", "Prescription"),
                            ("DiagnosticReport", "Diagnostic Report"),
                            ("DischargeSummary", "Discharge Summary"),
                            ("WellnessRecord", "Wellness Record"),
                            ("HealthDocumentRecord", "Health Document Record"),
                            ("ImmunizationRecord", "Immunization Record"),
                        ],
                        default="OPConsultation",
                        max_length=40,
                    ),
                ),
                ("fhir_bundle", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("acked", "Acknowledged"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("eka_request_id", models.CharField(blank=True, max_length=120)),
                ("eka_response", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "care_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="abdm.carecontext",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
